  gitops:

    name: Update GitOps Repository

    runs-on: ubuntu-latest

    needs: docker



    steps:

      - name: Checkout GitOps Repository

        uses: actions/checkout@v4

        with:

          repository: sandip2025/skillpulse-gitops

          token: ${{ secrets.GITOPS_TOKEN }}

          path: gitops



      - name: Update Backend Image

        run: |

          sed -i "s|image:.*skillpulse-backend.*|image: ${{ secrets.DOCKER_USERNAME }}/skillpulse-backend:latest|g" gitops/k8s/backend-deployment.yaml



      - name: Update Frontend Image

        run: |

          sed -i "s|image:.*skillpulse-frontend.*|image: ${{ secrets.DOCKER_USERNAME }}/skillpulse-frontend:latest|g" gitops/k8s/frontend-deployment.yaml



      - name: Configure Git

        run: |

          git config --global user.name "github-actions[bot]"

          git config --global user.email "github-actions[bot]@users.noreply.github.com"



      - name: Commit and Push Changes

        run: |

          cd gitops

          git add .



          if git diff --cached --quiet; then

            echo "No changes detected"

            exit 0

          fi



          git commit -m "Update SkillPulse images"

          git push https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/sandip2025/skillpulse-gitops.git main

```
