
name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

          echo "== CONTEXTS =="
          kubectl config get-contexts

          echo "== CURRENT CONTEXT =="
          kubectl config current-context || true

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
