name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

          echo "=== CONTEXT LIST ==="
          kubectl config get-contexts

          echo "=== SET CONTEXT ==="
          kubectl config use-context kind-skillpulse || true

          kubectl config current-context

      - name: Deploy
        run: kubectl apply -f k8s/
